db.permissions.drop();

db.permissions.insertMany([
  // Political
  {
    name: "get_political",
    displayName: "Lấy danh sách địa giới hành chính",
    method: "GET",
    path: "^/political/(province|district|commune)$",
    type: "admin",
    description: "",
  },

  // Parking
  {
    name: "get_parking",
    displayName: "Xem danh sách bãi đỗ xe",
    method: "GET",
    path: "^/parking$",
    type: "admin",
    description: "",
  },
  {
    name: "create_parking",
    displayName: "Tạo bãi đỗ xe",
    method: "POST",
    path: "^/parking$",
    type: "admin",
    description: "",
  },
  {
    name: "update_parking",
    displayName: "Sửa thông tin bãi đỗ xe",
    method: "PUT",
    path: "^/parking/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "get_single_parking",
    displayName: "Xem thông tin bãi đỗ",
    method: "GET",
    path: "^/parking/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "delete_parking",
    displayName: "Xóa bãi đỗ xe",
    method: "DELETE",
    path: "^/parking/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },

  // No parking
  {
    name: "get_no_parking",
    displayName: "Xem danh sách khu vực cấm đỗ xe",
    method: "GET",
    path: "^/no_parking$",
    type: "admin",
    description: "",
  },
  {
    name: "create_no_parking",
    displayName: "Tạo khu vực cấm đỗ xe",
    method: "POST",
    path: "^/no_parking$",
    type: "admin",
    description: "",
  },
  {
    name: "update_no_parking",
    displayName: "Sửa thông tin khu vực cấm đỗ xe",
    method: "PUT",
    path: "^/no_parking/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "get_single_no_parking",
    displayName: "Lấy thông tin khu vực cấm đỗ xe",
    method: "GET",
    path: "^/no_parking/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "delete_no_parking",
    displayName: "Xóa khu vực cấm đỗ xe",
    method: "DELETE",
    path: "^/no_parking/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },

  // Posts
  {
    name: "get_posts",
    displayName: "Lấy danh sách tin tức",
    method: "GET",
    path: "^/posts$",
    type: "admin",
    description: "",
  },
  {
    name: "create_post",
    displayName: "Tạo tin tức",
    method: "POST",
    path: "^/posts$",
    type: "admin",
    description: "",
  },
  {
    name: "update_post",
    displayName: "Sửa nội dung tin tức",
    method: "PUT",
    path: "^/posts/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "get_single_post",
    displayName: "Lấy nội dung tin tức",
    method: "GET",
    path: "^/posts/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "delete_post",
    displayName: "Xóa tin tức",
    method: "DELETE",
    path: "^/posts/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },

  // Violations
  {
    name: "get_violations",
    displayName: "Lấy danh sách vi phạm",
    method: "GET",
    path: "^/violations$",
    type: "admin",
    description: "",
  },
  {
    name: "get_single_violation",
    displayName: "Lấy thông tin vi phạm",
    method: "GET",
    path: "^/violations/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "update_violation",
    displayName: "Sửa thông tin vi phạm",
    method: "PUT",
    path: "^/violations/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "delete_violation",
    displayName: "Xóa vi phạm",
    method: "DELETE",
    path: "^/violations/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },

  // Cameras
  {
    name: "get_cameras",
    displayName: "Xem danh sách camera",
    method: "GET",
    path: "^/camera$",
    type: "admin",
    description: "",
  },
  {
    name: "get_single_camera",
    displayName: "Xem thông tin camera",
    method: "GET",
    path: "^/camera/[a-f0-9]{24}/(connect|functions|params)$",
    type: "admin",
    description: "",
  },
  {
    name: "delete_camera",
    displayName: "Xóa camera",
    method: "DELETE",
    path: "^/camera/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "get_camera_group",
    displayName: "Xem danh sách nhóm camera",
    method: "GET",
    path: "^/camera/group$",
    type: "admin",
    description: "",
  },
  {
    name: "get_zones",
    displayName: "Xem danh sách các vùng nhận dạng",
    method: "GET",
    path: "^/camera/zone$",
    type: "admin",
    description: "",
  },
  {
    name: "create_camera",
    displayName: "Thêm camera",
    method: "POST",
    path: "^/camera$",
    type: "admin",
    description: "",
  },
  {
    name: "update_camera",
    displayName: "Sửa thông tin camera",
    method: "PUT",
    path: "^/camera/[a-f0-9]{24}/(connect|params|functions)$",
    type: "admin",
    description: "",
  },

  // Roles
  {
    name: "get_roles",
    displayName: "Lấy danh sách các nhóm người dùng",
    method: "GET",
    path: "^/roles$",
    type: "admin",
    description: "",
  },
  {
    name: "get_single_role",
    displayName: "Lấy thông tin nhóm người dùng",
    method: "GET",
    path: "^/roles/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "create_role",
    displayName: "Tạo nhóm người dùng",
    method: "GET",
    path: "^/roles/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "update_role",
    displayName: "Sửa thông tin nhóm người dùng",
    method: "PUT",
    path: "^/roles/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "delete_role",
    displayName: "Xóa nhóm người dùng",
    method: "DELETE",
    path: "^/roles/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "get_permissions",
    displayName: "Xem danh sách các hành động",
    method: "GET",
    path: "^/permissions$",
    type: "admin",
    description: "",
  },

  // Users
  {
    name: "get_user",
    displayName: "Xem thông tin người dùng",
    method: "GET",
    path: "^/users/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },
  {
    name: "update_user",
    displayName: "Sửa thông tin người dùng",
    method: "PUT",
    path: "^/users/[a-f0-9]{24}$",
    type: "admin",
    description: "",
  },

  // Followlist
  {
    name: "get_followlist",
    displayName: "Xem danh sách camera đang theo dõi",
    method: "GET",
    path: "^/followlist$",
    type: "admin",
    description: "",
  },
  {
    name: "get_camera_unfollowed",
    displayName: "Xem danh sách camera chưa được theo dõi",
    method: "GET",
    path: "^/not_followed$",
    type: "admin",
    description: "",
  },
  {
    name: "add_camera_to_followlist",
    displayName: "Thêm camera vào danh sách theo dõi",
    method: "POST",
    path: "^/followlist$",
    type: "admin",
    description: "",
  },
  {
    name: "remove_camera_from_followlist",
    displayName: "Xóa camera khỏi danh sách theo dõi",
    method: "DELETE",
    path: "^/followlist$",
    type: "admin",
    description: "",
  },

  // Parking Fee ???
  {
    name: "fee",
    displayName: "Quản lý thu phí",
    method: "GET",
    path: "^/fee$",
    type: "admin",
    description: "",
  },

  // Notifications
  {
    name: "get_notifications",
    displayName: "Xem danh sách thông báo",
    method: "GET",
    path: "^/notifications$",
    type: "admin",
    description: "",
  },
  {
    name: "mark_read",
    displayName: "Đánh dấu thông báo là đã đọc",
    method: "PUT",
    path: "^/notifications/read$",
    type: "admin",
    description: "",
  },

  // Local Computer

  // Logs

  // Cài đặt

  {
    name: "get_plate_numbers",
    displayName: "Lấy danh sách biển số của người dùng",
    method: "GET",
    path: "^/social/[a-f0-9]{24}/plate_numbers",
    type: "public",
    description: "",
  },
  {
    name: "add_plate_number",
    displayName: "Thêm biển số vào danh sách của người dùng",
    method: "POST",
    path: "^/social/[a-f0-9]{24}/plate_numbers",
    type: "public",
    description: "",
  },
  {
    name: "delete_plate_number",
    displayName: "Xóa biển số ra khỏi danh sách của người dùng",
    method: "DELETE",
    path: "^/social/[a-f0-9]{24}/plate_numbers",
    type: "public",
    description: "",
  },
  {
    name: "update_status",
    displayName: "Cập nhật trạng thái người dùng",
    method: "PUT",
    path: "^/social/status$",
    type: "public",
    description: "",
  },
  {
    name: "logout",
    displayName: "Đăng xuất",
    method: "POST",
    path: "^/social/logout$",
    type: "public",
    description: "",
  },
]);
